config/routes.rb
Rails.application.routes.draw do
  # Static pages
  get  '/regulamin1', to: 'static_pages#regulamin1'
  get  '/regulamin2', to: 'static_pages#regulamin2'
  get  '/reklama', to: 'static_pages#reklama'
  get  '/dla_prasy', to: 'static_pages#dla_prasy'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    sessions: 'customized_devise/sessions',
    registrations: 'customized_devise/registrations'
  }

  namespace :admin do
    root 'forum/sections#index'
    namespace :forum do
      resources :sections, except: :show
      resources :threads, except: [:new, :create] do
        get :close, on: :member
      end
      resources :posts, except: :show
    end
    namespace :newsletter do
      resources :subscribers, except: :show
      resources :categories, except: :show
    end
    resources :user_categories, except: :show
    resources :users, except: [:new, :create, :show]
    resources :states, except: :show
    resources :branches, except: :show
    resources :events, except: :show
    resources :articles, except: :show
    resources :companies, only: [:index, :edit, :update]
    resources :departments, except: :show
    resources :publications, except: :show
    resources :definitions, except: :show
    resources :calendars, except: :show
    resources :government_plans, except: :show
    resources :banners, except: :show
    resources :links, except: :show
    resources :useful_links, except: :show
    resources :product_payments, except: :show
    resources :email_templates, only: [:index, :edit, :update]
    resources :removal_categories, except: :show do
      resources :removals, except: :show
    end
    resources :trees, except: :show
    resources :coefficients, except: :show

    #
    # Info point
    #
    resources :manual_categories, except: :show do
      resources :manuals, except: :show
    end
    resources :document_categories, except: :show do
      resources :documents, except: :show
    end
    resources :wastes, except: :show
    resources :recycling_categories, except: :show do
      resources :recyclings, except: :show
    end
    resources :environment_water_categories, except: :show do
      resources :environment_waters, except: :show
    end
    resources :gaz_categories, except: :show do
      resources :gazs, except: :show
    end
    resources :water_categories, except: :show do
      resources :waters, except: :show
    end
    resources :gasoline_categories, except: :show do
      resources :gasolines, except: :show
    end
    resources :sng_categories, except: :show do
      resources :sngs, except: :show
    end
    resources :diesel_categories, except: :show do
      resources :diesels, except: :show
    end

    #
    # /Info point
    #

    resources :laws, except: :show
    resources :project_categories, except: :show do
      resources :projects, except: :show
    end
    resources :interpretation_categories, except: :show do
      resources :interpretations, except: :show
    end
    resources :union_document_categories, except: :show do
      resources :union_documents, except: :show
    end
  end

  resources :banners, only: :show
  resources :search, only: [:index]
  resources :articles, only: [:index, :show]
  resources :companies, only: [:index, :show, :new, :create]
  resources :departments, only: :index
  resources :definitions, only: :index
  resources :events, only: [:index, :show]

  #
  # Info point
  #
  namespace :manuals do
    resources :categories, only: [:index, :show]
  end
  resources :manuals, only: :show
  resources :documents, only: :index
  resources :publications, only: :index
  resources :calendars, only: [:index, :show]
  resources :government_plans, only: [:index, :show]
  resources :wastes, only: :index
  resources :waste_fees, only: :index
  namespace :recyclings do
    resources :categories, only: :index
  end
  namespace :removals do
    resources :categories, only: :index
  end
  resources :trees, only: [:index, :show]
  post  'trees/calculate'
  namespace :environment_waters do
    resources :categories, only: :index
  end
  namespace :gazs do
    resources :categories, only: :index
  end
  namespace :waters do
    resources :categories, only: :index
  end
  namespace :gasolines do
    resources :categories, only: :index
  end
  namespace :sngs do
    resources :categories, only: :index
  end
  namespace :diesels do
    resources :categories, only: :index
  end
  resources :useful_links, only: :index

  #
  # /Info point
  #

  #
  # Laws
  #
  resources :laws, only: :index

  namespace :union_documents do
    resources :categories, only: [:index, :show]
  end

  namespace :projects do
    resources :categories, only: [:index, :show]
  end
  resources :projects, only: :show


  namespace :interpretations do
    resources :categories, only: [:index, :show]
  end
  resources :interpretations, only: :show
  #
  # /Laws
  #

  resources :project_categories, only: :index do
    resources :projects, only: [:index, :show]
  end

  namespace :forum do
    root 'sections#index'
    resources :threads, only: [:new, :create]
    resources :sections, only: [:index, :show] do
      resources :threads, only: [:index]
    end
    resources :threads, only: [] do
      resources :posts, only: [:index, :create]
    end
  end

  namespace :newsletter do
    resources :subscribers, only: [:create]
  end

  root 'welcome#index'
end

app/controllers/admin/project_categories_controller.rb
module Admin
  class ProjectCategoriesController < BaseController
    before_action :set_and_authorize_category, only: [:edit, :update, :destroy]

    # GET /admin/project_categories
    def index
      authorize [:admin, ::Project::Category]
      @project_categories = ::Project::Category.all
    end

    # GET /admin/project_categories/new
    def new
      authorize [:admin, ::Project::Category]
      @project_category = ::Project::Category.new
    end

    # POST /admin/project_categories
    def create
      authorize [:admin, ::Project::Category]
      @project_category = ::Project::Category.new(category_params)
      if @project_category.save
        redirect_to admin_project_categories_url, notice: t('shared.created')
      else
        render :new
      end
    end

    # GET /admin/project_categories/:id/edit
    def edit
    end

    # PATCH/PUT /admin/project_categories/:id
    def update
      if @project_category.update(category_params)
        redirect_to admin_project_categories_url, notice: t('shared.updated')
      else
        render :edit
      end
    end

    # DELETE /admin/project_categories/:id
    def destroy
      if @project_category.destroy
        redirect_to admin_project_categories_url, notice: t('shared.destroyed')
      else
        redirect_to admin_project_categories_url, alert: t('shared.not_destroyed')
      end
    end

    private

    def set_and_authorize_category
      @project_category = ::Project::Category.find(params[:id])
      authorize [:admin, @project_category]
    end

    def category_params
      params.require(:project_category).permit(:name)
    end
  end
end

app/views/admin/project_categories/_form.html.slim
= simple_form_for [:admin, @project_category], as: :project_category, html: { class: 'form-horizontal' } do |f|
  .box.box-primary
    .box-body
      = f.input :name
    .box-footer
      => link_to t('shared.back'), admin_project_categories_path, class: 'btn btn-default'
      = f.button :submit, f.object.persisted? ? t('shared.update') : t('shared.create'), class: 'btn pull-right'

app/views/admin/project_categories/edit.html.slim
section.content-header
  .actions.pull-right
    - if policy([:admin, @project_category]).destroy?
      => link_to admin_project_category_path(@project_category), method: :delete, data: { confirm: t('shared.are_you_sure') }, class: 'btn btn-danger'
        i.fa.fa-trash>
        =t 'shared.destroy'
  h1
    i.fa.fa-send>
    =t '.title'
section.content
  = render 'form'

app/views/admin/project_categories/index.html.slim
section.content-header
  h1
    i.fa.fa-send>
    =>t '.title'
    small=t '.subtitle'

section.content
  .box
    .box-header.with-border
      - if policy([:admin, ::Project::Category]).new?
        = link_to t('.actions.add'), new_admin_project_category_path, class: 'btn btn-success'
    .box-body.no-padding
      table#project_categories.table.table-striped
        thead
          tr
            th=t '.table.name'
            th
        tbody
          - @project_categories.each do |project_category|
            tr id=dom_id(project_category)
              td= link_to project_category.name, admin_project_category_projects_path(project_category)
              td
                .btn-group
                  a.dropdown-toggle data-toggle='dropdown' href='#'
                    i.fa.fa-cog
                  ul.dropdown-menu.pull-right
                    - if policy([:admin, project_category]).edit?
                      li
                        = link_to edit_admin_project_category_path(project_category) do
                          i.fa.fa-pencil>
                          =t 'shared.edit'
                      - if policy([:admin, project_category]).destroy?
                        li
                          = link_to admin_project_category_path(project_category), method: :delete, data: { confirm: t('shared.are_you_sure') } do
                            i.fa.fa-trash>
                            =t 'shared.destroy'

app/views/admin/project_categories/new.html.slim
section.content-header
  h1
    i.fa.fa-send>
    =t '.title'
section.content
  = render 'form'